In [95]:
import pandas as pd

df = pd.read_csv("Housing.csv")

df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [96]:
df.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

In [97]:
df.corr(numeric_only=True)["price"].sort_values(ascending=False)

price        1.000000
area         0.535997
bathrooms    0.517545
stories      0.420712
parking      0.384394
bedrooms     0.366494
Name: price, dtype: float64

In [98]:
from sklearn.model_selection import train_test_split

X=df.drop("price",axis=1)
y=df["price"]
X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.2,random_state=42)

In [99]:
print(X_test.isnull().sum())

area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [100]:
import numpy as np

In [101]:
def remove_outliers(df,col):
    Q1=df[col].quantile(0.25)
    Q3=df[col].quantile(0.75)
    IQR=Q3-Q1
    return df[(df[col]>=Q1 - 1.5*IQR) & (df[col] <= Q3 + 1.5*IQR)]
X_train["price"] = y_train
print(X_train)
X_train=remove_outliers(X_train,"price")

y_train = X_train["price"]
X_train = X_train.drop("price",axis=1)

     area  bedrooms  bathrooms  stories mainroad guestroom basement  \
46   6000         3          2        4      yes        no       no
93   7200         3          2        1      yes        no      yes
335  3816         2          1        1      yes        no      yes
412  2610         3          1        2      yes        no      yes
471  3750         3          1        2      yes        no       no
..    ...       ...        ...      ...      ...       ...      ...
71   6000         4          2        4      yes        no       no
106  5450         4          2        1      yes        no      yes
270  4500         3          2        3      yes        no       no
435  4040         2          1        1      yes        no       no
102  5500         3          2        4      yes       yes       no

    hotwaterheating airconditioning  parking prefarea furnishingstatus  \
46               no             yes        1       no        furnished
93               no             yes        3       no   semi-furnished
335              no             yes        2       no        furnished
412              no              no        0      yes      unfurnished
471              no              no        0       no      unfurnished
..              ...             ...      ...      ...              ...
71               no             yes        0       no      unfurnished
106              no             yes        0      yes   semi-furnished
270             yes              no        1       no        furnished
435              no              no        0       no      unfurnished
102              no             yes        1       no   semi-furnished

       price
46   7525000
93   6300000
335  3920000
412  3430000
471  3010000
..       ...
71   6755000
106  6160000
270  4340000
435  3290000
102  6195000

[436 rows x 13 columns]

In [102]:
X_train

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
46,6000,3,2,4,yes,no,no,no,yes,1,no,furnished
93,7200,3,2,1,yes,no,yes,no,yes,3,no,semi-furnished
335,3816,2,1,1,yes,no,yes,no,yes,2,no,furnished
412,2610,3,1,2,yes,no,yes,no,no,0,yes,unfurnished
471,3750,3,1,2,yes,no,no,no,no,0,no,unfurnished
...,...,...,...,...,...,...,...,...,...,...,...,...
71,6000,4,2,4,yes,no,no,no,yes,0,no,unfurnished
106,5450,4,2,1,yes,no,yes,no,yes,0,yes,semi-furnished
270,4500,3,2,3,yes,no,no,yes,no,1,no,furnished
435,4040,2,1,1,yes,no,no,no,no,0,no,unfurnished
102,5500,3,2,4,yes,yes,no,no,yes,1,no,semi-furnished

In [103]:
cat_cols = X_train.select_dtypes(include=['object']).columns
X_train = pd.get_dummies(X_train,columns=cat_cols,drop_first=True)
X_test = pd.get_dummies(X_test,columns=cat_cols,drop_first=True)
# X_train,X_test = X_train.align(X_test,join='left',axis=1,fill_value=0)

/tmp/ipykernel_17470/24634764.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = X_train.select_dtypes(include=['object']).columns

In [104]:
X_test

,area,bedrooms,bathrooms,stories,parking,mainroad_yes,guestroom_yes,basement_yes,hotwaterheating_yes,airconditioning_yes,prefarea_yes,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
316,5900,4,2,2,1,False,False,True,False,False,False,False,True
77,6500,3,2,3,0,True,False,False,False,True,True,False,False
360,4040,2,1,1,0,True,False,False,False,False,False,True,False
90,5000,3,1,2,0,True,False,False,False,True,False,True,False
493,3960,3,1,1,0,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15,6000,4,1,2,2,True,False,True,False,False,False,True,False
357,6930,4,1,2,1,False,False,False,False,False,False,False,False
39,6000,4,2,4,1,True,False,False,False,True,False,True,False
54,6000,3,2,2,1,True,True,False,False,True,False,True,False
155,6100,3,2,1,2,True,False,True,False,False,True,False,False

In [105]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.fit_transform(X_test)

In [106]:
X_test

,area,bedrooms,bathrooms,stories,parking,mainroad_yes,guestroom_yes,basement_yes,hotwaterheating_yes,airconditioning_yes,prefarea_yes,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
316,5900,4,2,2,1,False,False,True,False,False,False,False,True
77,6500,3,2,3,0,True,False,False,False,True,True,False,False
360,4040,2,1,1,0,True,False,False,False,False,False,True,False
90,5000,3,1,2,0,True,False,False,False,True,False,True,False
493,3960,3,1,1,0,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15,6000,4,1,2,2,True,False,True,False,False,False,True,False
357,6930,4,1,2,1,False,False,False,False,False,False,False,False
39,6000,4,2,4,1,True,False,False,False,True,False,True,False
54,6000,3,2,2,1,True,True,False,False,True,False,True,False
155,6100,3,2,1,2,True,False,True,False,False,True,False,False

In [108]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
# model=RandomForestRegressor()
model=GradientBoostingRegressor()
model.fit(X_train,y_train)
pred = model.predict(X_test)
print(mean_absolute_error(y_test,pred))
importances = pd.Series(model.feature_importances_,index=X_train.columns)
importances.sort_values(ascending=False).head(10)

998478.6349702555

area                            0.476927
bathrooms                       0.127308
airconditioning_yes             0.082957
stories                         0.067601
parking                         0.045585
basement_yes                    0.043255
furnishingstatus_unfurnished    0.041273
bedrooms                        0.039483
prefarea_yes                    0.029466
mainroad_yes                    0.018875
dtype: float64

In [109]:
# X_train=X_train.drop("hotwaterheating_yes",axis=1)

In [110]:
X_train

,area,bedrooms,bathrooms,stories,parking,mainroad_yes,guestroom_yes,basement_yes,hotwaterheating_yes,airconditioning_yes,prefarea_yes,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
46,6000,3,2,4,1,True,False,False,False,True,False,False,False
93,7200,3,2,1,3,True,False,True,False,True,False,True,False
335,3816,2,1,1,2,True,False,True,False,True,False,False,False
412,2610,3,1,2,0,True,False,True,False,False,True,False,True
471,3750,3,1,2,0,True,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,6000,4,2,4,0,True,False,False,False,True,False,False,True
106,5450,4,2,1,0,True,False,True,False,True,True,True,False
270,4500,3,2,3,1,True,False,False,True,False,False,False,False
435,4040,2,1,1,0,True,False,False,False,False,False,False,True
102,5500,3,2,4,1,True,True,False,False,True,False,True,False

In [68]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
lr=LinearRegression()
lr.fit(X_train,y_train)
pred1=lr.predict(X_test)
mean_absolute_error(y_test,pred1)

967311.7633955728

In [69]:
lr2 = LinearRegression()
lr2.fit(X_train_scaled,y_train)
pred2 = lr2.predict(X_test_scaled)
mean_absolute_error(y_test,pred2)

1004551.0501347185

In [75]:
X_train_drop=X_train.drop("area",axis=1)
X_test_drop=X_test.drop("area",axis=1)
model=RandomForestRegressor()
model.fit(X_train_drop,y_train)
pred=model.predict(X_test_drop)
mean_absolute_error(y_test,pred)

1102179.2916458722

In [79]:
from sklearn.preprocessing import LabelEncoder
df2 = df.copy()
for col in df2.select_dtypes(include=['object']).columns:
    le=LabelEncoder()
    df2[col]=le.fit_transform(df2[col])

/tmp/ipykernel_17470/1698166117.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df2.select_dtypes(include=['object']).columns:

In [87]:
X=df2.drop("price",axis=1)
y=df2["price"]
X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.2,random_state=42)

In [88]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
lr=LinearRegression()
lr.fit(X_train,y_train)
pred1=lr.predict(X_test)
mean_absolute_error(y_test,pred1)

503245.2974099002

In [90]:
model=RandomForestRegressor()
model.fit(X_train,y_train)
pred = model.predict(X_test)
print(mean_absolute_error(y_test,pred))
importances = pd.Series(model.feature_importances_,index=X_train.columns)
importances.sort_values(ascending=False).head(10)

287538.447706422

area                0.509295
price_per_area      0.439224
bathrooms           0.024623
parking             0.006262
bedrooms            0.005783
furnishingstatus    0.004095
stories             0.002735
prefarea            0.002643
basement            0.001808
airconditioning     0.001674
dtype: float64

In [85]:
df2["price_per_area"] = df2["price"]/df2["area"]

In [91]:
from sklearn.linear_model import Ridge
from sklearn.ensemble import GradientBoostingRegressor

In [92]:
train_pred = model.predict(X_train)
test_pred = model.predict(X_test)
print(mean_absolute_error(y_train,train_pred))
mean_absolute_error(y_test,test_pred)

78379.95206422017

287538.447706422